/** Declaration file generated by dts-gen */

export = get_google_fonts;

declare class get_google_fonts {
    constructor(...args: any[]);

    download(...args: any[]): void;

    getConfig(...args: any[]): void;

    repairInput(...args: any[]): void;

    setConfig(...args: any[]): void;

    static constructUrl(...args: any[]): void;

}

declare namespace get_google_fonts {
    namespace prototype {
        function download(...args: any[]): void;

        function getConfig(...args: any[]): void;

        function repairInput(...args: any[]): void;

        function setConfig(...args: any[]): void;

    }

}

